services:
  fft-denoise:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fft-denoise
    image: ghcr.io/huotrithy/fft-denoise:v1.0.0
    environment:
      - TZ=Asia/Phnom_Penh
    ports:
      - "127.0.0.1:8503:8503"
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://fft-denoise:8503/_stcore/health || exit 1"]
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

    volumes:
      - ./.streamlit:/app/.streamlit
  